Repository uprm-inso4115-2024-2025-s2/semester-project-DungeonCrawlers, pull requests merged in 2025-02, with the labels that each got.

#46 Tile map wall Collision
  floor&walls.tres
  world.tscn
Labels: Pending Approval, Dungeon Team

#69 Adjusted character textures and added project setting
  project.godot
  world.tscn
Labels: Bug, Entity Team

#102 WASD and arrow keys
  player.gd
Labels: Entity Team

#105 finished `Autotile Terrain for High Walls`
  high_walls.tres
  world.tscn
Labels: Bug, Dungeon Team

#104 added collision to atlas high walls
  world.tscn
Labels: Bug

#111 Attack implementation
  Sprites/weapon_axe.png
  Sprites/weapon_axe.png.import
  Sprites/weapon_baton_with_spikes.png
  Sprites/weapon_baton_with_spikes.png.import
  Sprites/weapon_big_hammer.png
  Sprites/weapon_big_hammer.png.import
  player.gd
  project.godot
  world.tscn
Labels: Entity Team
