Repository uprm-inso4115-2024-2025-s2/semester-project-DungeonCrawlers, pull requests merged in 2025-04, with the labels that each got.

#281 Added Strength Potion Art Assets
  Potion Assets/Strenght Pill.png
  Potion Assets/Strenght Pill.png.import
Labels: Entity Team, Completed

#224 116 integrate settings menu with pause menu
  health_hud.tscn
  main_menu.tscn
  pause_menu_ui.gd
  project.godot
  settings_menu.gd
  world.tscn
Labels: Multiplayer Team, Completed

#294 Main fix+sounds+bug fix+ally functionallityt
  Mobs/Allies/ally.gd
  Mobs/Enemies/Demon.gd
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_attack.ogg
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_attack.ogg.import
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_death.ogg
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_death.ogg.import
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_hurt.ogg
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_hurt.ogg.import
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_run.ogg
  addons/SimpleTemplateMainMenu-1.0.1/assets/Sfx/player_run.ogg.import
  health_hud.tscn
  how_to_play.gd
  main_menu.tscn
  pause_menu_ui.gd
  player.gd
  project.godot
  settings_menu.gd
  world.gd
  world.tscn
Labels: Entity Team
