Repository uprm-inso4115-2024-2025-s2/semester-project-DungeonCrawlers, pull requests merged in 2025-03, with the labels that each got.

#132 Fixing Bug error
  Mobs/Allies/ally_2D.tscn
  Mobs/Allies/ally_behavior.gd
  Mobs/Allies/ally_spawner.gd
  Mobs/Allies/ally_spawner.tscn
  player.gd
  world.gd
  world.tscn
Labels: Dungeon Team

#143 Completed trap behavior. It is not a instance
  world.tscn
Labels: TL Approved, Dungeon Team, Completed

#144 added keyboard_art.png to files
  Sprites/keyboard_art.png.png
  Sprites/keyboard_art.png.png.import
Labels: Pending Approval, Entity Team, Completed

#154 added interactable chest
  0x72_DungeonTilesetII_v1.7/chests.png
  0x72_DungeonTilesetII_v1.7/chests.png.import
  chest.gd
  project.godot
  world.tscn
Labels: Approved, TL Approved, Dungeon Team, Completed

#160 Settingsmenu
  ControlSettings.tscn
  GraphicsSettings.tscn
  UI/AudioSettings.gd
  UI/AudioSettings.tscn
  UI/ControlSettings.gd
  UI/ControlSettings.tscn
  UI/GraphicsSettings.gd
  UI/GraphicsSettings.tscn
  settings_menu.gd
  settings_menu.tscn
Labels: Multiplayer Team

#172 Door completed. To open door press e
  door.gd
  traps.gd
  world.tscn
Labels: TL Approved, Dungeon Team

#174 Doors
  door.gd
  traps.gd
  world.tscn
Labels: TL Approved, Dungeon Team, Completed

#169 AI for enemies and Allies was implemented
  .gitignore
  Mobs/Allies/ally.gd
  Mobs/Allies/ally_2D.tscn
  Mobs/Allies/ally_behavior.gd
  Mobs/Enemies/Demon.gd
  Mobs/Enemies/enemy_2D.tscn
  canvas_layer.gd
  world.tscn
Labels: Entity Team

#217 Implementation of victory and loss conditions
  Mobs/Enemies/Demon.gd
  UI/game_over_screen.gd
  UI/game_over_screen.tscn
  player.gd
  world.gd
  world.tscn
Labels: Entity Team

#223 Boss behaviour
  Idle.gd
  Mobs/Enemies/boss.gd
  Mobs/Enemies/boss.tscn
  Mobs/Enemies/state_control.gd
  Mobs/Enemies/wander.gd
  Mobs/EnemyMobs/node_2d.tscn
  boss_summons.gd
  canvas_layer.gd
  state.gd
  sword_projectile.gd
  sword_projectile.tscn
  world.gd
  world.tscn
Labels: Entity Team

#218 Implement Switch and Button
  Switch.gd
  button.gd
  door.gd
  world.tscn
Labels: TL Approved, Dungeon Team, Completed

#225 linked settings to menu
  main_menu.gd
  settings_menu.gd
  settings_menu.tscn
Labels: Multiplayer Team

#233 added how to play scene
  Sprites/keyboard_art.png.png
  how_to_play.gd
  how_to_play.tscn
  how_to_play_Asset/Keyboard Pixel art.png
  how_to_play_Asset/Keyboard Pixel art.png.import
  how_to_play_Asset/MinecraftRegular-Bmg3.otf
  how_to_play_Asset/MinecraftRegular-Bmg3.otf.import
  pause_menu_ui.gd
  project.godot
  world.gd
  world.tscn
Labels: Entity Team, Completed
